services:
    php:
        build:
            context: .
            dockerfile: ./dockify/Dockerfile
        container_name: dockify-php
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./dockify/config/php/php.ini:/usr/local/etc/php/php.ini
            - ./dockify/config/php/php-fpm.conf:/usr/local/etc/php-fpm.d/php-fpm-custom.conf
            - ./dockify/logs/php:/var/log/php
        ports:
            - "8000:8000"
        depends_on:
            - mysql
            - redis
            - memcached
        networks:
            - dockify-network
    nginx:
        image: nginx:alpine
        container_name: dockify-nginx
        volumes:
            - ./:/var/www
            - ./dockify/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./dockify/logs/nginx:/var/log/nginx
        ports:
            - "8080:80"
        depends_on:
            - php
        networks:
            - dockify-network
    mysql:
        image: mysql:latest
        container_name: dockify-mysql
        expose:
            - "3306"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - ./dockify/data/mysql:/var/lib/mysql
            - ./dockify/config/mysql/my.cnf:/etc/mysql/my.cnf
            - ./dockify/logs/mysql:/var/log/mysql
        networks:
            - dockify-network
    redis:
        image: redis:alpine
        container_name: dockify-redis
        expose:
            - "6379"
        ports:
            - "6379:6379"
        volumes:
            - ./dockify/data/redis:/data
            - ./dockify/config/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./dockify/logs/redis:/var/log/redis
        networks:
            - dockify-network
    memcached:
        image: memcached:alpine
        container_name: dockify-memcached
        expose:
            - "11211"
        ports:
            - "11211:11211"
        volumes:
            - ./dockify/config/memcached/memcached.conf:/etc/memcached.conf
            - ./dockify/logs/memcached:/var/log/memcached
        networks:
            - dockify-network
networks:
    dockify-network:
        driver: bridge

volumes:
    dockify-data:
    dockify-database: